import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useForm, SubmitHandler, useFormContext } from "react-hook-form";
import { FC } from "react";
const inter = Inter({ subsets: ["latin"] });

type Inputs = {
  example: string;
  exampleRequired: string;
  test: string;
};

function NestedInput() {
  const { register } = useFormContext(); // retrieve all hook methods

  console.log(register);

  return <input {...register("test")} />;
}

const InnerComponent: FC = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = (data) => console.log(data);

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input defaultValue="test" {...register("example")} />
      <input {...register("exampleRequired", { required: true })} />
      <NestedInput />
      {errors.exampleRequired && <span>This field is required</span>}
      <input type="submit" />
    </form>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <InnerComponent />
      </main>
    </>
  );
}
